.gitignore, README.md, content/charter/_index.en.md, content/contribute/_index.en.md, content/e2eclinical/_index.en.md, content/e2eclinical/esub/_index.en.md, content/e2eclinical/tlg/_index.en.md, content/nonpharma/_index.en.md, content/support/_index.en.md, data/people/contributors.yaml, layouts/index.html, layouts/partials/contributors.html, scripts/add_contributions.R
Tackled a bunch of issues to get it closer to v1
Please reference any related issues here: #17 #26
=> V1 release

content/faq/index.en.md
PR to develop to test updates on UAT site
updated FAQ around validation
Please reference any related issues here (using `#issuenumber`): #67 
=> 67 - update validation FAQ

content/contribute/_index.en.md
PR to develop to test updates on UAT site
updated the contribute page with extra bullet to explain the hosted shield/badge option and link to this sub-page
Please reference any related issues here (using `#issuenumber`): #69 
=> 69 - added bullet on hosted shield

content/opensource/_index.en.md
PR to develop to test updates on UAT site
new page added for useful open source links - see content/opensource/_index.en.md
Please reference any related issues here (using `#issuenumber`): #51 
=> 51 new page for useful open source links

content/opensource/_index.en.md
PR to develop to test updates on UAT site
made some minor updates for issue 51 to make it look better on the site
Please reference any related issues here (using `#issuenumber`): #51 
=> 51 update weight for ordering and icon

content/e2eclinical/metadata/_index.en.md, content/e2eclinical/sdtm/_index.en.md, data/packages/metatools.yaml, data/packages/oak.yaml, data/packages/sdtmchecks.yaml
Added metatools and sdtmchecks packages
Please reference any related issues here (using `#issuenumber`): #102, #111
=> Added metatools and sdtmchecks packages

content/nonpharma/_index.en.md
Minor update requested
Please reference any related issues here (using `#issuenumber`): closes #118 
=> closes #118

content/e2eclinical/tlg/_index.en.md
=> Nest is OS

content/contribute/lead/_index.en.md, content/e2eclinical/sdtm/_index.en.md, content/e2eclinical/tlg/_index.en.md, data/packages/datacutr.yaml, data/packages/roak.yaml, data/packages/sdtmchecks.yaml, data/packages/tfrmt.yaml
Few SDTM and TLG updates
Please reference any related issues here (using `#issuenumber`): #134 #121 #125 
=> Few SDTM and TLG updates

config/_default/config.toml, content/e2eclinical/_index.en.md
Add examples and youtube links
Please reference any related issues here (using `#issuenumber`): #137 #138
=> Add examples and youtube links

content/contribute/lead/_index.en.md, content/e2eclinical/adam/_index.en.md, data/packages/admiralonco.yaml, data/packages/admiralophtha.yaml, data/packages/admiralvaccine.yaml
admiral new packages
Please reference any related issues here (using `#issuenumber`): #141
=> Develop - admiral new packages

content/contribute/wg/_index.en.md
=> typo update

content/nonpharma/_index.en.md
Just adding the `mmrm` package to the statistics packages.
@rossfarrugia fyi
=> add mmrm package to stats packages

content/charter/_index.en.md, content/contribute/council/_index.en.md, content/contribute/wg/_index.en.md, content/e2eclinical/tlg/_index.en.md, data/packages/chevron.yaml, scripts/add_contributions.R
Please reference any related issues here (using `#issuenumber`): #157 #158 
People to notify: @core-team
=> Updates from RStudio feedback

content/e2eclinical/tlg/_index.en.md, data/packages/envsetup.yaml, data/packages/nest.yaml
Remove nest branding
Please reference any related issues here (using `#issuenumber`): #162
People to notify: @core-team
=> Remove nest branding

config/_default/config.toml, content/faq/index.en.md, data/packages/logrx.yaml
Added r/pharma talk link and few clean ups
Please reference any related issues here (using `#issuenumber`):  #174 #175
=> Few minor issues

README.md, content/contribute/lead/_index.en.md, data/packages/admiral.yaml
=> update admiral link to last release

static/council meeting minutes/2023-02-21.md
Added Feb 2023 council meet minutes - no impact to site
=> Add latest council meeting minutes

data/packages/rtables.yaml
=> Update rtables location

data/people/amuehlig.yaml  , data/people/lewandt.yaml
=> Add Axel to data wg

content/e2eclinical/tlg/_index.en.md, data/packages/tidytlg.yaml
Please reference any related issues here (using `#issuenumber`): #215 
=> Closes #215 bug tidytlg doc link broken

static/council meeting minutes/2023-03-21.md
=> Add March council minutes

content/contribute/lead/_index.en.md, content/e2eclinical/validation/_index.en.md, data/packages/riskassessment.yaml, data/packages/riskmetric.yaml
New validation packages and CRAN criteria update
Please reference any related issues here (using `#issuenumber`): #195 #221
=> New validation packages and CRAN criteria update

.github/workflows/pipeline.yml, .github/workflows/update-universe.yml
Use pinned R version, update runner & checkout action
=> Use pinned R version, update runner & checkout action

data/packages/riskassessment.yaml, data/packages/riskmetric.yaml, static/council meeting minutes/2023-04-18.md
=> April council meeting minutes

data/packages/riskmetric.yaml, static/council meeting minutes/2023-04-18.md
=> workflow fixes

content/e2eclinical/sdtm/_index.en.md, data/packages/datacutr.yaml
added datacutr - approved by data WG
Please reference any related issues here (using `#issuenumber`): #220
=> closes #220 add datacutr

static/council meeting minutes/2023-05-16.md
=> latest council minutes

content/e2eclinical/tlg/_index.en.md, content/nonpharma/_index.en.md, data/packages/ggsurvfit.yaml
add ggsurvfit and remove repeat visR from nonpharma page
Please reference any related issues here (using `#issuenumber`): #231
=> closes #231 add ggsurvfit

static/council meeting minutes/2023-07-18.md
July council meeting minutes - no impact to site
=> July meeting minutes

content/e2eclinical/developers/_index.en.md
clarify thevalidatoR
Please reference any related issues here (using `#issuenumber`): #257 
=> closes #257 clarify thevalidatoR

static/council meeting minutes/2023-09-26.md
=> Council minutes

config/_default/config.toml, content/e2eclinical/_index.en.md, content/nonpharma/_index.en.md, data/nonpharma/lintr.yaml, data/nonpharma/styler.yaml
Add styler to list of nonpharma packages and replace old examples site with new quarto book link
Please reference any related issues here (using `#issuenumber`): #266 #267
=> Minor updates to site

content/e2eclinical/utility/_index.en.md, content/faq/index.en.md, data/packages/datasetjson.yaml
add datasetjson
Please reference any related issues here (using `#issuenumber`): #261 #270
=> add datasetjson

static/council meeting minutes/2023-10-17.md
=> council minutes for Oct

content/charter/_index.en.md, content/contribute/council/_index.en.md, content/e2eclinical/_index.en.md
Opinionated to Curated minor updates
Please reference any related issues here (using `#issuenumber`): #280
=> Opinionated to Curated minor updates

content/e2eclinical/tlg/_index.en.md, data/packages/chevron.yaml, data/packages/falcon.yaml
=> Move up chevron on TLG page and mention upcoming falcon rename

content/contribute/ic/_index.en.md, content/e2eclinical/tlg/_index.en.md, data/packages/cards.yaml, data/packages/tfrmtbuilder.yaml
Add {cards}, {tfrmtbuilder} and tips for new contributors
Please reference any related issues here (using `#issuenumber`): #284 #286 #287
=> Closes #284 #286 #287

.github/workflows/pipeline.yml
This version of the action is unbroken
=> Use checkout v4.1.1

.github/workflows/pipeline.yml, content/e2eclinical/tlg/_index.en.md, data/packages/cardinal.yaml, data/packages/falcon.yaml, static/council meeting minutes/2024-06-18.md
Please reference any related issues here (using `#issuenumber`): #299 
=> falcon rename and council minutes

content/contribute/_index.en.md, content/contribute/lead/_index.en.md
=> Minor: 2 missed WG changes in last PR

content/contribute/wg/_index.en.md
=> minor: add blog community

content/e2eclinical/tlg/_index.en.md, data/packages/cardx.yaml, data/packages/gtsummary.yaml
=> Add new packages

content/e2eclinical/adam/_index.en.md, data/packages/admiralpeds.yaml, static/council meeting minutes/2024-08-20.md
=> Add admiralpeds

content/contribute/wg/_index.en.md
Closes #322 
Fixes the `Data Visualisation and Open Source Technology (DVOST) working group` link in the [Community members](https://pharmaverse.org/contribute/wg/) section of the pharmaverse website.
Please reference any related issues here (using `#issuenumber`): #322 
=> fix: fix link path

.github/workflows/pipeline.yml
FYI - I haven't done a full review, but hoping the only consequence of removing this code that relies on the s3 buckets is the site wont have badges
=> Comment out the code that uses the s3 buckets

data/packages/aNCA.yaml
=> add aNCA logo

content/e2eclinical/sdtm/_index.en.md, content/opensource/_index.en.md, data/packages/aNCA.yaml
This should fix #330 #328 #315 #115 FYI @rossfarrugia
=> Fix badges

.github/workflows/pipeline.yml
Adding back in build - was working on dev
=> add badges back to pipeline

renv.lock, scripts/add_badges.R
=> Make 'pharmaverse' badges 

.github/workflows/pipeline.yml, config/staging/config.toml, themes/godocs-1/assets/scss/templates/_navigation.scss
Please reference any related issues here (using `#issuenumber`): #250 
=> 250 PHUSE logo persistent in navbar of all pages

.github/workflows/pipeline.yml, scripts/add_badges.R
- Fixed `add_badges.R` script logic.
=> Fix add badge script

.github/workflows/pipeline.yml, renv.lock, scripts/add_badges.R, scripts/get_badge_data.R, scripts/get_pharmaverse_pkgs.R
- Added script to pull the latest badge data
Please reference any related issues here (using `#issuenumber`): #342 
=> Add script to update badge data

content/library/index.en.md, static/council meeting minutes/2024-11-19.md
Please reference any related issues here (using `#issuenumber`): #344
=> council meet minutes and fix broken link

content/contribute/lead/_index.en.md
=> closes #346 fix broken link

static/council meeting minutes/2024-12-17.md
=> council meeting minutes

data/packages/pkglite.yaml
add link to python version of pkglite
Please reference any related issues here (using `#issuenumber`): #350 
=> closes #350 add link to python version of pkglite

content/contribute/wg/_index.en.md
adoption group no longer meets
Please reference any related issues here (using `#issuenumber`): #352
=> #352 adoption group no longer meets

data/packages/admiralmetabolic.yaml, data/packages/autoslider.yaml, data/packages/risk.assessr.yaml
=> fix badges for new packages

scripts/get_badge_data.R
- Fixes logic to pull cran data for `pharmaverse` packages.
=> fix: fetch package cran data

content/e2eclinical/utility/_index.en.md, data/packages/whirl.yaml
=> closes #376 add whirl to pharmaverse

content/e2eclinical/utility/_index.en.md, data/packages/connector.yaml
=> closes #378 add connector package

data/packages/aNCA.yaml
- Specified path for the new aNCA logo.
=> Update aNCA logo in the landing page

content/e2eclinical/utility/_index.en.md
- Specified correct path for new aNCA logo
=> Update aNCA logo

renv.lock, scripts/add_hexwall_network.R, scripts/ppnetwork.R
- Implemented GitStats logic to create visual network diagram
=> Update to GitStats package from GithubMetrics

content/e2eclinical/developers/_index.en.md, data/packages/pharmaverseraw.yaml
add pharmaverseraw for SDTM examples
Please reference any related issues here (using `#issuenumber`): #380 
=> closes #380 add pharmaverseraw for SDTM examples
